### ISSUE TITLE
[Style] Add Template Inheritance

### ISSUE THREAD

**Issue by KKhushhalR2405** [arpit456jain/CodingEasy#165]
Contributions are needed to restructure the templates and use [template inheritance](https://docs.djangoproject.com/en/4.0/ref/templates/language/)  to improve code reusability.

**Task**
Code for navbar and footer is written in every template which has to be removed. The base.html defines the skeleton HTML template and all other templates should inherit from it using `block`.

Below are the files to be restructured 

<details>
  <summary>C</summary>

  - [ ] [Constants/Literals](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/C/Constants/Literals) ||  Assigned to 
  - [ ] [Data_Types](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/C/Data_Types) || Assigned to 
  - [ ] [Modifiers](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/C/Modifiers) || Assigned to 
  - [ ] [Variable_Types](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/C/Variable_Types) || Assigned to 
  - [ ] [c.html](https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/C/c.html) || Assigned to 
</details>

<details>
  <summary>CPP</summary>

- [ ] [Constants/Literals](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/CPP/Constants/Literals) || Assigned to 
- [ ] [Data_Types](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/CPP/Data_Types) || Assigned to 
- [ ] [Modifiers](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/CPP/Modifiers) || Assigned to 
- [ ] [Variable_Types](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/CPP/Variable_Types) || Assigned to 
- [ ] [cpp.html](https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/CPP/cpp.html) || Assigned to 
</details>

<details>
  <summary>Git_GitHub</summary>

- [ ] [git.html](https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/Git_GitHub/git.html) || Assigned to
</details>

<details>
  <summary>Hierarchical Clustering</summary>

- [ ] [Hierarchical Clustering.html](https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/Hierarchical%20Clustering/Hierarchical%20Clustering.html)  || Assigned to

</details>

<details>
  <summary>Html</summary>

- [ ] [Basic](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/Html/Basic) || Assigned to @sripor62
- [ ] [Images](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/Html/Images) || Assigned to
- [ ] [Links](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/Html/Links) || Assigned to
- [ ] [Lists](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/Html/Lists) || Assigned to
- [ ] [Style](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/Html/Style) || Assigned to
- [ ] [Table](https://github.com/arpit456jain/CodingEasy/tree/master/templates/home/Html/Table) || Assigned to
- [ ] [html.html](https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/Html/html.html) || Assigned to

</details>

## Note
All contributors are requested to 
1) go through [base.html](https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/base.html) and [button.html](https://github.com/arpit456jain/CodingEasy/blob/master/templates/home/bootstrap/button/button.html) to get an idea of how to proceed.

2) take up to 3 files for ```Level2``` PR or 1 file for ```Level1``` PR
3) comment the file names you want to restructure and get assigned
4) make sure code doesn't break 😉
5) do not use  ```closes #165 ```  message in your PR, instead use ```closes part of #165 ```.

Path to all template: ``` templates\home```
Parent template: ```base.html```

**Comment by KKhushhalR2405** [comment]
> hey ! I want to work on the file html/basic.Can you assign it to me?

Assigning you the same

**Comment by arpit456jain** [comment]
> hey ! I want to work on the file html/basic.Can you assign it to me?

hey @sripor62 actually we just added template inheritance to project  please check out the project and do let us know if it can be added to anymore page create a new issue for that

**Comment by sripor62** [comment]
In the contact us a toggling sidebar or  navbar can be added.
